# Generated by Django 2.2.6 on 2019-11-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hostel', 'room_num')},
        ),
    ]
