# Generated by Django 2.2.6 on 2019-10-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0003_room_room_alloted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['hostel', 'room_num']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
    ]
